#!/bin/bash

IP=$(cat /etc/IP)
cor1='\033[41;1;37m'
cor2='\033[44;1;37m'
scor='\033[0m'

if [[ -f /etc/.domain ]]; then 
   Host=$(cat /etc/.domain)
else
   Host="Your_domain_here"
fi

# Gerar client.ovpn
newclient() {
    cp /etc/openvpn/client-common.txt ~/$1.ovpn
    echo "<ca>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/ca.crt >>~/$1.ovpn
    echo "</ca>" >>~/$1.ovpn
    echo "<cert>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >>~/$1.ovpn
    echo "</cert>" >>~/$1.ovpn
    echo "<key>" >>~/$1.ovpn
    cat /etc/openvpn/easy-rsa/pki/private/$1.key >>~/$1.ovpn
    echo "</key>" >>~/$1.ovpn
    echo "<tls-auth>" >>~/$1.ovpn
    cat /etc/openvpn/ta.key >>~/$1.ovpn
    echo "</tls-auth>" >>~/$1.ovpn
}

fun_geraovpn() {
    [[ "$respost" = @(s|S) ]] && {
        cd /etc/openvpn/easy-rsa/
        ./easyrsa build-client-full $username nopass
        newclient "$username"
        sed -e "s;auth-user-pass;<auth-user-pass>\n$username\n$password\n</auth-user-pass>;g" /root/$username.ovpn >/root/tmp.ovpn && mv -f /root/tmp.ovpn /root/$username.ovpn
    } || {
        cd /etc/openvpn/easy-rsa/
        ./easyrsa build-client-full $username nopass
        newclient "$username"
    }
} >/dev/null 2>&1

[[ -e /etc/openvpn/server.conf ]] && {
    _Port=$(grep -w 'port' /etc/openvpn/server.conf | awk {'print $2'})
    hst=$(sed -n '8 p' /etc/openvpn/client-common.txt | awk {'print $4'})
    rmt=$(sed -n '7 p' /etc/openvpn/client-common.txt)
    hedr=$(sed -n '8 p' /etc/openvpn/client-common.txt)
    prxy=$(sed -n '9 p' /etc/openvpn/client-common.txt)
    rmt2='/VPSMANAGER?'
    rmt3='www.vivo.com.br 8088'
    prx='200.142.130.104'
    payload1='#payload "HTTP/1.0 [crlf]Host: m.youtube.com[crlf]CONNECT HTTP/1.0[crlf][crlf]|[crlf]"'
    payload2='#payload "CONNECT 127.0.0.1:1194[split][crlf] HTTP/1.0 [crlf][crlf]#"'
    vivo1="portalrecarga.vivo.com.br/recarga"
    vivo2="portalrecarga.vivo.com.br/controle/"
    vivo3="navegue.vivo.com.br/pre/"
    vivo4="navegue.vivo.com.br/controle/"
    vivo5="www.vivo.com.br"
    oi="d1n212ccp6ldpw.cloudfront.net"
    bypass="net_gateway"
    cert01="/etc/openvpn/client-common.txt"
    if [[ "$hst" == "$vivo1" ]]; then
        Host="Portal Recarga"
    elif [[ "$hst" == "$vivo2" ]]; then
        Host="Recarga contole"
    elif [[ "$hst" == "$vivo3" ]]; then
        Host="Portal Navegue"
    elif [[ "$hst" == "$vivo4" ]]; then
        Host="Nav controle"
    elif [[ "$hst" == "$IP:$_Port" ]]; then
        Host="Vivo MMS"
    elif [[ "$hst" == "$oi" ]]; then
        Host="Oi"
    elif [[ "$hst" == "$bypass" ]]; then
        Host="Modo Bypass"
    elif [[ "$hedr" == "$payload1" ]]; then
        Host="OPEN SOCKS"
    elif [[ "$hedr" == "$payload2" ]]; then
        Host="OPEN SQUID"
    else
        Host="Customizado"
    fi
}

fun_bar() {
    comando[0]="$1"
    comando[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${comando[0]} >/dev/null 2>&1
        ${comando[1]} >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "\033[1;33mPlease Wait.. \033[1;37m- \033[1;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[1;31m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[1;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "\033[1;33mPlease Wait.. \033[1;37m- \033[1;33m["
    done
    echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}

fun_edithost() {
    clear
    echo -e "\E[44;1;37m          CHANGE HOST OVPN            \E[0m"
    echo ""
    echo -e "\033[1;33mHOST IN USE\033[1;37m: \033[1;32m$Host"
    echo ""
    echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;33mVIVO RECHARGE"
    echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;33mVIVO NAVIGATE PRE"
    echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;33mOPEN SOCKS \033[1;31m[\033[1;32mAPP MOD\033[1;31m]"
    echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;33mOPEN SQUID \033[1;31m[\033[1;32mAPP MOD\033[1;31m]"
    echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;33mVIVO MMS \033[1;31m[\033[1;37mAPN: \033[1;32mmms.vivo.com.br\033[1;31m]"
    echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;33mMODO BYPASS \033[1;31m[\033[1;32mOPEN + INJECTOR\033[1;31m]"
    echo -e "\033[1;31m[\033[1;36m7\033[1;31m] \033[1;33mALL HOSTS \033[1;31m[\033[1;32m1 OVPN OF EACH\033[1;31m]"
    echo -e "\033[1;31m[\033[1;36m8\033[1;31m] \033[1;33mEDIT MANUALLY"
    echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;33mCOME BACK"
    echo ""
    echo -ne "\033[1;32mWHICH HOST DO YOU WANT TO USE \033[1;33m?\033[1;37m "
    read respo
    [[ -z "$respo" ]] && {
        echo -e "\n\033[1;31mInvalid option!"
        sleep 2
        fun_edithost
    }
    if [[ "$respo" = '1' ]]; then
        sed -i "s;$rmt;$vivo1;g" /etc/openvpn/client-common.txt
        Host="Portal Recarga"
        fun_edithost
    elif [[ "$respo" = '2' ]]; then
        sed -i "s;$rmt;$vivo2;g" /etc/openvpn/client-common.txt
        Host="Recarga controle"
        fun_edithost
    elif [[ "$respo" = '3' ]]; then
        sed -i "s;${rmt};${payload1};g" /etc/openvpn/client-common.txt
        Host="OPEN SOCKS"
        fun_edithost
    elif [[ "$respo" = '4' ]]; then
        sed -i "s;${rmt};${payload2};g" /etc/openvpn/client-common.txt
        Host="OPEN SQUID"
        fun_edithost
    elif [[ "$respo" = '5' ]]; then
        sed -i "s;${rmt};${rmt2};g" /etc/openvpn/client-common.txt
        Host="Vivo MMS"
        fun_edithost
    elif [[ "$respo" = '6' ]]; then
        sed -i "s;${rmt};${prxy};g" /etc/openvpn/client-common.txt
        Host="Modo Bypass"
        fun_edithost
    elif [[ "$respo" = '7' ]]; then
        fun_geraovpn
        fun_bar
        echo -e "\n\033[1;37m ALL HOSTS OVPN GENERATED ! \033[1;32m"
        echo ""
        sleep 2
        fun_edithost
    elif [[ "$respo" = '8' ]]; then
        nano /etc/openvpn/client-common.txt
        fun_edithost
    elif [[ "$respo" = '0' ]]; then
        clear
        exit
    else
        echo -e "\n\033[1;31mInvalid option!"
        sleep 2
        fun_edithost
    fi
}

fun_adduser() {
    clear
    echo -e "\E[44;1;37m            ADD SSH USER            \E[0m"
    echo ""
    read -p "Enter username: " username
    read -p "Enter password: " password
    echo "Creating user $username..."
    
    # Generate URL for the SSH user
    url="http://yourdomain.com/ssh/${username}"

    # Add SSH user and generate VPN profile
    useradd -m -s /bin/bash $username
    echo "$username:$password" | chpasswd
    fun_geraovpn

    echo -e "\n\033[1;37mUser created successfully!"
    echo -e "\033[1;37mSSH User URL: \033[1;32m$url"
    echo -e "\033[1;37mOVPN File: \033[1;32m/root/$username.ovpn"
    echo ""
    sleep 2
    fun_mainmenu
}

fun_mainmenu() {
    clear
    echo -e "\E[44;1;37m        SSH AND VPN MANAGER        \E[0m"
    echo ""
    echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;33mAdd SSH User"
    echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;33mEdit OVPN Hosts"
    echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;33mExit"
    echo ""
    echo -ne "\033[1;32mChoose an option: \033[1;37m"
    read option
    case $option in
        1) fun_adduser ;;
        2) fun_edithost ;;
        0) exit ;;
        *) echo -e "\033[1;31mInvalid option!"; sleep 2; fun_mainmenu ;;
    esac
}

fun_mainmenu
